CREATE TABLE IF NOT EXISTS "sale_prodline_info" (
                                                    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                    "name" varchar,
                                                    "parent_id" bigint NOT NULL,
                                                    "creator" varchar DEFAULT '',
                                                    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    "updater" varchar DEFAULT '',
                                                    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    "tenant_id" bigint,
                                                    "deleted" bit NOT NULL DEFAULT FALSE,
                                                    PRIMARY KEY ("id")
) COMMENT '产品线';

CREATE TABLE IF NOT EXISTS "sale_production_marsaleclass" (
                                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                              "name" varchar,
                                                              "parent_id" bigint,
                                                              "creator" varchar DEFAULT '',
                                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              "updater" varchar DEFAULT '',
                                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                              "tenant_id" bigint,
                                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                                              PRIMARY KEY ("id")
) COMMENT '销售分类';
CREATE TABLE IF NOT EXISTS "sale_production_marbasclass" (
                                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                             "name" varchar,
                                                             "parent_id" bigint,
                                                             "creator" varchar DEFAULT '',
                                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             "updater" varchar DEFAULT '',
                                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                             "tenant_id" bigint,
                                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                                             PRIMARY KEY ("id")
) COMMENT '物料分类';