CREATE TABLE IF NOT EXISTS "sale_prodline_info" (
                                                    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                    "name" varchar,
                                                    "parent_id" bigint NOT NULL,
                                                    "creator" varchar DEFAULT '',
                                                    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    "updater" varchar DEFAULT '',
                                                    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    "tenant_id" bigint,
                                                    "deleted" bit NOT NULL DEFAULT FALSE,
                                                    PRIMARY KEY ("id")
) COMMENT '产品线';

CREATE TABLE IF NOT EXISTS "sale_production_marsaleclass" (
                                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                              "name" varchar,
                                                              "parent_id" bigint,
                                                              "creator" varchar DEFAULT '',
                                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              "updater" varchar DEFAULT '',
                                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                              "tenant_id" bigint,
                                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                                              PRIMARY KEY ("id")
) COMMENT '销售分类';
CREATE TABLE IF NOT EXISTS "sale_production_marbasclass" (
                                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                             "name" varchar,
                                                             "parent_id" bigint,
                                                             "creator" varchar DEFAULT '',
                                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             "updater" varchar DEFAULT '',
                                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                             "tenant_id" bigint,
                                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                                             PRIMARY KEY ("id")
) COMMENT '物料分类';

CREATE TABLE IF NOT EXISTS "sale_production_info" (
                                                      "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                      "name" varchar,
                                                      "marsaleclass_id" bigint,
                                                      "marbasclass_id" bigint,
                                                      "prodline_id" bigint,
                                                      "spec" varchar,
                                                      "price" varchar,
                                                      "protein" varchar,
                                                      "creator" varchar DEFAULT '',
                                                      "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      "updater" varchar DEFAULT '',
                                                      "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                      "tenant_id" bigint,
                                                      "deleted" bit NOT NULL DEFAULT FALSE,
                                                      PRIMARY KEY ("id")
) COMMENT '物料信息表';

CREATE TABLE IF NOT EXISTS "sale_production_compete_info" (
                                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                              "production_id" bigint,
                                                              "dept_id" bigint,
                                                              "price" varchar,
                                                              "creator" varchar DEFAULT '',
                                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              "updater" varchar DEFAULT '',
                                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                              "tenant_id" bigint,
                                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                                              PRIMARY KEY ("id")
) COMMENT '工厂竞品管理';

CREATE TABLE IF NOT EXISTS "sale_compete_info" (
                                                   "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   "brand" varchar,
                                                   "prod_name" varchar,
                                                   "spec" varchar,
                                                   "compete_id" bigint,
                                                   "price" varchar,
                                                   "creator" varchar DEFAULT '',
                                                   "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                   "updater" varchar DEFAULT '',
                                                   "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                   "tenant_id" bigint,
                                                   "deleted" bit NOT NULL DEFAULT FALSE,
                                                   PRIMARY KEY ("id")
) COMMENT '竞品信息';

CREATE TABLE IF NOT EXISTS "sale_compete_info_sub" (
                                                       "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                       "parent_id" bigint NOT NULL,
                                                       "change_date" varchar NOT NULL,
                                                       "price_changes" varchar NOT NULL,
                                                       "file_id" varchar,
                                                       "creator" varchar DEFAULT '',
                                                       "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                       "updater" varchar DEFAULT '',
                                                       "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                       "tenant_id" bigint,
                                                       "deleted" bit NOT NULL DEFAULT FALSE,
                                                       PRIMARY KEY ("id")
) COMMENT '竞品信息子表';

CREATE TABLE IF NOT EXISTS "sale_customer_sales_detail" (
                                                            "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                            "customer_code" varchar,
                                                            "customer_name" varchar,
                                                            "zone_code" varchar,
                                                            "zone_name" varchar,
                                                            "area_name" varchar,
                                                            "area_code" varchar,
                                                            "dept_code" varchar,
                                                            "dept_name" varchar,
                                                            "employee_pk" varchar,
                                                            "employee_code" varchar,
                                                            "employee_name" varchar,
                                                            "sale_month" varchar,
                                                            "sale_date" varchar,
                                                            "daily_sales" varchar,
                                                            "monthly_cumulative_sales" varchar,
                                                            "creator" varchar DEFAULT '',
                                                            "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                            "updater" varchar DEFAULT '',
                                                            "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                            "tenant_id" bigint,
                                                            "deleted" bit NOT NULL DEFAULT FALSE,
                                                            PRIMARY KEY ("id")
) COMMENT '客户销售明细';


-- 将该建表 SQL 语句，添加到 yudao-module-sale-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "sale_decline_warning" (
                                                      "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                      "zone_code" varchar,
                                                      "zone_name" varchar,
                                                      "area_name" varchar,
                                                      "area_code" varchar,
                                                      "summarize" varchar,
                                                      "reason_analysis" varchar,
                                                      "improvement_measure" varchar,
                                                      "file_id" varchar,
                                                      "compete_time" varchar,
                                                      "process_instance_id" bigint,
                                                      "creator" varchar DEFAULT '',
                                                      "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      "updater" varchar DEFAULT '',
                                                      "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                      "tenant_id" bigint,
                                                      "deleted" bit NOT NULL DEFAULT FALSE,
                                                      PRIMARY KEY ("id")
) COMMENT '销量预警';

CREATE TABLE IF NOT EXISTS "sale_decline_warning_sub" (
                                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                          "customer_name" varchar,
                                                          "customer_code" varchar,
                                                          "employee_name" varchar,
                                                          "dept_name" varchar,
                                                          "pre_month_sales" varchar,
                                                          "curr_month_sales" varchar,
                                                          "decline_ratio" varchar,
                                                          "decline_num" varchar,
                                                          "parent_id" bigint,
                                                          "creator" varchar DEFAULT '',
                                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          "updater" varchar DEFAULT '',
                                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                          "tenant_id" bigint,
                                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                                          PRIMARY KEY ("id")
) COMMENT '销量下降预警子表';
