-- 将该建表 SQL 语句，添加到 yudao-module-strain-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "strain_culture_medium_data_info" (
                                                                 "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                                 "code" varchar NOT NULL,
                                                                 "name" varchar NOT NULL,
                                                                 "sterilization_conditions" varchar NOT NULL,
                                                                 "usage" varchar NOT NULL,
                                                                 "category" varchar NOT NULL,
                                                                 "formula" varchar NOT NULL,
                                                                 "create_by" varchar,
                                                                 "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                 "update_by" varchar,
                                                                 "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                                 "remark" varchar,
                                                                 PRIMARY KEY ("id")
) COMMENT '培养基数据信息表';

-- 将该建表 SQL 语句，添加到 yudao-module-strain-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "strain_freezing_box_info" (
                                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                          "code" varchar,
                                                          "name" varchar,
                                                          "x_axis_capacity" int,
                                                          "y_axis_capacity" int,
                                                          "x_axis_code_type" varchar,
                                                          "y_axis_code_type" varchar,
                                                          "creator" varchar DEFAULT '',
                                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          "updater" varchar DEFAULT '',
                                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                          "remark" varchar,
                                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                                          PRIMARY KEY ("id")
) COMMENT '冷冻盒信息表';


CREATE TABLE IF NOT EXISTS "strain_freezing_tube_info" (
                                                           "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                           "code" varchar,
                                                           "name" varchar,
                                                           "capacity" int,
                                                           "volume_unit" varchar,
                                                           "creator" varchar DEFAULT '',
                                                           "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           "updater" varchar DEFAULT '',
                                                           "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                           "remark" varchar,
                                                           "deleted" bit NOT NULL DEFAULT FALSE,
                                                           PRIMARY KEY ("id")
) COMMENT '冷冻管基本信息表';

CREATE TABLE IF NOT EXISTS "strain_storage_area_info" (
                                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                          "code" varchar,
                                                          "name" varchar,
                                                          "location_info" varchar,
                                                          "creator" varchar DEFAULT '',
                                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          "updater" varchar DEFAULT '',
                                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                          "remark" varchar,
                                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                                          PRIMARY KEY ("id")
) COMMENT '存放区域信息表';

CREATE TABLE IF NOT EXISTS "strain_freezing_device_info" (
                                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                             "name" varchar NOT NULL,
                                                             "code" varchar NOT NULL,
                                                             "type" varchar NOT NULL,
                                                             "temperature" bigint,
                                                             "stroage_area_id" bigint NOT NULL,
                                                             "creator" varchar DEFAULT '',
                                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             "updater" varchar DEFAULT '',
                                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                             "remark" varchar,
                                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                                             PRIMARY KEY ("id")
) COMMENT '冷冻设备信息表';

CREATE TABLE IF NOT EXISTS "strain_freezing_device_hierarchy" (
                                                                  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                                  "parent_id" bigint,
                                                                  "freezing_device_id" bigint,
                                                                  "is_final_level" bit,
                                                                  "freezing_box_id" bigint,
                                                                  "creator" varchar DEFAULT '',
                                                                  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                  "updater" varchar DEFAULT '',
                                                                  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                                  "remark" varchar,
                                                                  "deleted" bit NOT NULL DEFAULT FALSE,
                                                                  "layer_type" varchar,
                                                                  PRIMARY KEY ("id")
) COMMENT '冷冻设备层级表';