-- 将该建表 SQL 语句，添加到 yudao-module-strain-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "strain_culture_medium_data_info" (
                                                                 "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                                 "code" varchar NOT NULL,
                                                                 "name" varchar NOT NULL,
                                                                 "sterilization_conditions" varchar NOT NULL,
                                                                 "usage" varchar NOT NULL,
                                                                 "category" varchar NOT NULL,
                                                                 "formula" varchar NOT NULL,
                                                                 "create_by" varchar,
                                                                 "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                 "update_by" varchar,
                                                                 "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                                 "remark" varchar,
                                                                 PRIMARY KEY ("id")
) COMMENT '培养基数据信息表';

